language: python

python:
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - pip install -r djangotutorial/requirements.txt

before_script:
  - cd djangotutorial
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_success:
  - coveralls