language: python

python:
  - "3.12"

install:
  - pip install -r djangotutorial/requirements.txt
  - pip install coverage 'coveralls[yaml]' flake8

before_script:
  - cd djangotutorial
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_success:
  - cd "$TRAVIS_BUILD_DIR"
  - coveralls --verbose

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "djangotutorial"
  env: "djangotutorial-env"
  bucket: "elasticbeanstalk-us-east-1-314323855341"
  edge: true
  on:
    branch: main
    python: "3.12"